name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    # Install dependencies using make install
    - name: Install dependencies
      run: |
        make install

    # Lint with flake8
    - name: Lint with flake8
      run: |
        # Stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    # Test the application using make run and curl
    - name: Run application
      run: |
        make run &
        sleep 10  # Give the server time to start
        curl -I http://localhost:3000  # Check if the application is accessible

    # Run tests with pytest
    - name: Test with pytest
      run: |
        pytest
